override-Annotation ergänzt und Verweiskommentar entfernt in `../reminder/` (Teil von #82)
willuhn/hibiscus pull request #118
Opened 2022-01-04 18:38 UTC by ruderphilipp

2022-01-26 00:47 UTC, meigelb requested changes
Warum hast Du das javadoc entfernt? Nun werden doch keine Links mehr zur überschriebenen Methode gezogen? Oder passiert das durch `@Override` automatisch?

2022-01-26 00:51 UTC, meigelb requested changes
Bitte https://github.com/willuhn/hibiscus/pull/118#pullrequestreview-863017238 beantworten oder beheben. Danke.

2022-01-26 08:13 UTC, ruderphilipp commented
> Warum hast Du das javadoc entfernt? Nun werden doch keine Links mehr zur überschriebenen Methode gezogen? Oder passiert das durch `@Override` automatisch?

Hallo @meigelb,
heute ist es so, dass die Verweise ausschließlich Kommentare sind, die weder von der IDE noch vom Compiler ausgewertet werden. Das heißt, es kann sein, dass die referenzierte Methode gar nicht mehr existiert oder umbenannt wurde.

Da es sich bei diesem Pullrequest um eines von mehreren Einzelteilen (eines je Modul) aus dem Pullrequest #82 handelt, damit en-block einfacher zu reviewen, zitiere ich meine Nachricht von dort:

> Dieser Pullrequest ergänzt überall im Code, wo Methoden bei Vererbungen überschrieben werden, die Annotation `@Override`. Somit wird nicht nur textuell darauf verwiesen, sondern durch den Compiler überprüft, ob die Methodensignatur korrekt ist. Auch hat so die IDE eine bessere Möglichkeit, die Vererbungsbeziehungen zu analysieren.
> 
> Der Verweis im Kommentar auf die Elternmethode wird ebenfalls gelöscht, da moderne IDEs direkt mit einer Tastenkombination dorthin springen bzw. den Javadoc-Text anzeigen können.

2022-02-08 22:53 UTC, meigelb commented
Ah, perfekt, Danke für das Zitat. Ich habe noch nicht ganz den Überblick (hier in github). 😇

2022-02-08 22:56 UTC, meigelb commented
> Da es sich bei diesem Pullrequest um eines von mehreren Einzelteilen (eines je Modul) aus dem Pullrequest #82 handelt, damit en-block einfacher zu reviewen

Bedeutet das nun etwa, dass ich mich mit dem Review hier auch freiwillig dazu bereiterklärt habe, die anderen 15 PRs des #82 zu reviewen? 🥴

2022-02-08 22:56 UTC, meigelb approved these changes

2022-02-10 13:27 UTC, ruderphilipp commented
> Bedeutet das nun etwa, dass ich mich mit dem Review hier auch freiwillig dazu bereiterklärt habe, die anderen 15 PRs des #82 zu reviewen?

Es ist alles freiwillig ;-)
Sechs Augen sehen mehr als vier! 
Ich habe gesehen, dass Du bereits drei weitere davon durchgeschaut hast (die wurden inzwischen auch gemerged). Vielen Dank!

2022-02-16 08:17 UTC, merged